version: "3.9"
services:
  strapi:
    image: registry.byniwee.cloud/node:latest
    restart: "unless-stopped"
    tty: true
    command: "sh -c 'cp /mnt/.env .env && yarn && yarn build && yarn develop'"
    user: root
    volumes:
      - ./app:/app
      - ./.env:/mnt/.env
    working_dir: /app
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`cms.niwee.fr`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"
      - "traefik.http.routers.strapi.tls.certresolver=cloudflare"

networks:
  web:
    external: true
